# Generated by Django 4.1.2 on 2022-10-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_de_viaje', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('hora_vuelo', models.IntegerField()),
                ('estadia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Colectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_de_viaje', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('hora_colectivo', models.IntegerField()),
                ('estadia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_de_viaje', models.CharField(max_length=50)),
                ('hotel_colectivo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('estadia', models.IntegerField()),
            ],
        ),
    ]
